"""history

Revision ID: 34e55a913ab2
Revises: 011_feat_0001_revise_workflow_states
Create Date: 2026-04-23 15:24:24.360158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34e55a913ab2'
down_revision = '011_feat_0001_revise_workflow_states'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_business_areas_business_area_id'), table_name='form_business_areas')
    op.drop_index(op.f('ix_form_business_areas_form_id'), table_name='form_business_areas')
    op.drop_table('form_business_areas')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_bac_business_area_id'), table_name='business_area_contacts')
    op.drop_index(op.f('ix_bac_contact_user_id'), table_name='business_area_contacts')
    op.drop_index(op.f('ix_bac_created_at'), table_name='business_area_contacts')
    op.create_index(op.f('ix_business_area_contacts_business_area_id'), 'business_area_contacts', ['business_area_id'], unique=False)
    op.create_index(op.f('ix_business_area_contacts_contact_user_id'), 'business_area_contacts', ['contact_user_id'], unique=False)
    op.create_index(op.f('ix_business_area_contacts_created_at'), 'business_area_contacts', ['created_at'], unique=False)
    op.drop_constraint(op.f('uq_business_areas_name'), 'business_areas', type_='unique')
    op.drop_index(op.f('ix_business_areas_name'), table_name='business_areas')
    op.create_index(op.f('ix_business_areas_name'), 'business_areas', ['name'], unique=True)
    op.drop_index(op.f('ix_form_downloads_form_version_id'), table_name='form_downloads')
    op.drop_index(op.f('ix_form_downloads_user_id'), table_name='form_downloads')
    op.create_index(op.f('ix_form_downloads_created_at'), 'form_downloads', ['created_at'], unique=False)
    op.create_index(op.f('ix_form_downloads_deleted_at'), 'form_downloads', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_fnp_created_at'), table_name='form_number_prefixes')
    op.drop_index(op.f('ix_fnp_deleted_at'), table_name='form_number_prefixes')
    op.drop_index(op.f('ix_fnp_is_active'), table_name='form_number_prefixes')
    op.drop_index(op.f('ix_fnp_prefix'), table_name='form_number_prefixes')
    op.drop_constraint(op.f('uq_form_number_prefixes_prefix'), 'form_number_prefixes', type_='unique')
    op.create_index(op.f('ix_form_number_prefixes_created_at'), 'form_number_prefixes', ['created_at'], unique=False)
    op.create_index(op.f('ix_form_number_prefixes_deleted_at'), 'form_number_prefixes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_form_number_prefixes_is_active'), 'form_number_prefixes', ['is_active'], unique=False)
    op.create_index(op.f('ix_form_number_prefixes_prefix'), 'form_number_prefixes', ['prefix'], unique=True)
    op.drop_index(op.f('ix_fnr_created_at'), table_name='form_number_reservations')
    op.drop_index(op.f('ix_fnr_deleted_at'), table_name='form_number_reservations')
    op.create_index(op.f('ix_form_number_reservations_created_at'), 'form_number_reservations', ['created_at'], unique=False)
    op.create_index(op.f('ix_form_number_reservations_deleted_at'), 'form_number_reservations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_form_number_reservations_expires_at'), 'form_number_reservations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_form_number_reservations_prefix_id'), 'form_number_reservations', ['prefix_id'], unique=False)
    op.create_index(op.f('ix_form_number_reservations_reserved_by_id'), 'form_number_reservations', ['reserved_by_id'], unique=False)
    op.drop_index(op.f('ix_form_previews_user_id'), table_name='form_previews')
    op.create_index(op.f('ix_form_previews_created_at'), 'form_previews', ['created_at'], unique=False)
    op.create_index(op.f('ix_form_previews_deleted_at'), 'form_previews', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_fra_approver_id'), table_name='form_reservation_approvers')
    op.drop_index(op.f('ix_fra_created_at'), table_name='form_reservation_approvers')
    op.drop_index(op.f('ix_fra_deleted_at'), table_name='form_reservation_approvers')
    op.drop_index(op.f('ix_fra_reservation_id'), table_name='form_reservation_approvers')
    op.create_index(op.f('ix_form_reservation_approvers_approver_id'), 'form_reservation_approvers', ['approver_id'], unique=False)
    op.create_index(op.f('ix_form_reservation_approvers_created_at'), 'form_reservation_approvers', ['created_at'], unique=False)
    op.create_index(op.f('ix_form_reservation_approvers_deleted_at'), 'form_reservation_approvers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_form_reservation_approvers_reservation_id'), 'form_reservation_approvers', ['reservation_id'], unique=False)
    op.drop_index(op.f('ix_form_versions_uploaded_by_id'), table_name='form_versions')
    op.drop_constraint(op.f('uq_form_version_number'), 'form_versions', type_='unique')
    op.create_index(op.f('ix_form_versions_created_at'), 'form_versions', ['created_at'], unique=False)
    op.create_unique_constraint('unique_form_version', 'form_versions', ['form_id', 'version_number'])
    op.drop_index(op.f('ix_form_workflow_triggered_by_id'), table_name='form_workflow')
    op.create_index(op.f('ix_form_workflow_created_at'), 'form_workflow', ['created_at'], unique=False)
    op.create_index(op.f('ix_form_workflow_deleted_at'), 'form_workflow', ['deleted_at'], unique=False)
    op.add_column('forms', sa.Column('business_area_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_forms_created_by_id'), table_name='forms')
    op.create_index('idx_forms_created_by', 'forms', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_forms_business_area_id'), 'forms', ['business_area_id'], unique=False)
    op.drop_constraint(op.f('fk_forms_form_number_reservation_id'), 'forms', type_='foreignkey')
    op.create_foreign_key(None, 'forms', 'business_areas', ['business_area_id'], ['id'])
    op.create_foreign_key(None, 'forms', 'form_number_reservations', ['form_number_reservation_id'], ['id'])
    op.drop_constraint(op.f('uq_roles_name'), 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_constraint(op.f('uq_user_role'), 'user_roles', type_='unique')
    op.create_index(op.f('ix_user_roles_created_at'), 'user_roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_roles_deleted_at'), 'user_roles', ['deleted_at'], unique=False)
    op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id'])
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_keycloak_id'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_keycloak_id'), table_name='users')
    op.create_index(op.f('ix_users_keycloak_id'), 'users', ['keycloak_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_keycloak_id'), table_name='users')
    op.create_index(op.f('ix_users_keycloak_id'), 'users', ['keycloak_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_users_keycloak_id'), 'users', ['keycloak_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.drop_index(op.f('ix_user_roles_deleted_at'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_created_at'), table_name='user_roles')
    op.create_unique_constraint(op.f('uq_user_role'), 'user_roles', ['user_id', 'role_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_unique_constraint(op.f('uq_roles_name'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'forms', type_='foreignkey')
    op.drop_constraint(None, 'forms', type_='foreignkey')
    op.create_foreign_key(op.f('fk_forms_form_number_reservation_id'), 'forms', 'form_number_reservations', ['form_number_reservation_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_forms_business_area_id'), table_name='forms')
    op.drop_index('idx_forms_created_by', table_name='forms')
    op.create_index(op.f('ix_forms_created_by_id'), 'forms', ['created_by_id'], unique=False)
    op.drop_column('forms', 'business_area_id')
    op.drop_index(op.f('ix_form_workflow_deleted_at'), table_name='form_workflow')
    op.drop_index(op.f('ix_form_workflow_created_at'), table_name='form_workflow')
    op.create_index(op.f('ix_form_workflow_triggered_by_id'), 'form_workflow', ['triggered_by_id'], unique=False)
    op.drop_constraint('unique_form_version', 'form_versions', type_='unique')
    op.drop_index(op.f('ix_form_versions_created_at'), table_name='form_versions')
    op.create_unique_constraint(op.f('uq_form_version_number'), 'form_versions', ['form_id', 'version_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_form_versions_uploaded_by_id'), 'form_versions', ['uploaded_by_id'], unique=False)
    op.drop_index(op.f('ix_form_reservation_approvers_reservation_id'), table_name='form_reservation_approvers')
    op.drop_index(op.f('ix_form_reservation_approvers_deleted_at'), table_name='form_reservation_approvers')
    op.drop_index(op.f('ix_form_reservation_approvers_created_at'), table_name='form_reservation_approvers')
    op.drop_index(op.f('ix_form_reservation_approvers_approver_id'), table_name='form_reservation_approvers')
    op.create_index(op.f('ix_fra_reservation_id'), 'form_reservation_approvers', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_fra_deleted_at'), 'form_reservation_approvers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fra_created_at'), 'form_reservation_approvers', ['created_at'], unique=False)
    op.create_index(op.f('ix_fra_approver_id'), 'form_reservation_approvers', ['approver_id'], unique=False)
    op.drop_index(op.f('ix_form_previews_deleted_at'), table_name='form_previews')
    op.drop_index(op.f('ix_form_previews_created_at'), table_name='form_previews')
    op.create_index(op.f('ix_form_previews_user_id'), 'form_previews', ['user_id'], unique=False)
    op.drop_index(op.f('ix_form_number_reservations_reserved_by_id'), table_name='form_number_reservations')
    op.drop_index(op.f('ix_form_number_reservations_prefix_id'), table_name='form_number_reservations')
    op.drop_index(op.f('ix_form_number_reservations_expires_at'), table_name='form_number_reservations')
    op.drop_index(op.f('ix_form_number_reservations_deleted_at'), table_name='form_number_reservations')
    op.drop_index(op.f('ix_form_number_reservations_created_at'), table_name='form_number_reservations')
    op.create_index(op.f('ix_fnr_deleted_at'), 'form_number_reservations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fnr_created_at'), 'form_number_reservations', ['created_at'], unique=False)
    op.drop_index(op.f('ix_form_number_prefixes_prefix'), table_name='form_number_prefixes')
    op.drop_index(op.f('ix_form_number_prefixes_is_active'), table_name='form_number_prefixes')
    op.drop_index(op.f('ix_form_number_prefixes_deleted_at'), table_name='form_number_prefixes')
    op.drop_index(op.f('ix_form_number_prefixes_created_at'), table_name='form_number_prefixes')
    op.create_unique_constraint(op.f('uq_form_number_prefixes_prefix'), 'form_number_prefixes', ['prefix'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_fnp_prefix'), 'form_number_prefixes', ['prefix'], unique=True)
    op.create_index(op.f('ix_fnp_is_active'), 'form_number_prefixes', ['is_active'], unique=False)
    op.create_index(op.f('ix_fnp_deleted_at'), 'form_number_prefixes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fnp_created_at'), 'form_number_prefixes', ['created_at'], unique=False)
    op.drop_index(op.f('ix_form_downloads_deleted_at'), table_name='form_downloads')
    op.drop_index(op.f('ix_form_downloads_created_at'), table_name='form_downloads')
    op.create_index(op.f('ix_form_downloads_user_id'), 'form_downloads', ['user_id'], unique=False)
    op.create_index(op.f('ix_form_downloads_form_version_id'), 'form_downloads', ['form_version_id'], unique=False)
    op.drop_index(op.f('ix_business_areas_name'), table_name='business_areas')
    op.create_index(op.f('ix_business_areas_name'), 'business_areas', ['name'], unique=False)
    op.create_unique_constraint(op.f('uq_business_areas_name'), 'business_areas', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_business_area_contacts_created_at'), table_name='business_area_contacts')
    op.drop_index(op.f('ix_business_area_contacts_contact_user_id'), table_name='business_area_contacts')
    op.drop_index(op.f('ix_business_area_contacts_business_area_id'), table_name='business_area_contacts')
    op.create_index(op.f('ix_bac_created_at'), 'business_area_contacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_bac_contact_user_id'), 'business_area_contacts', ['contact_user_id'], unique=False)
    op.create_index(op.f('ix_bac_business_area_id'), 'business_area_contacts', ['business_area_id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('form_business_areas',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('form_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('business_area_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_area_id'], ['business_areas.id'], name=op.f('form_business_areas_business_area_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], name=op.f('form_business_areas_form_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('form_business_areas_pkey')),
    sa.UniqueConstraint('form_id', 'business_area_id', name=op.f('uq_form_business_area'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_form_business_areas_form_id'), 'form_business_areas', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_business_areas_business_area_id'), 'form_business_areas', ['business_area_id'], unique=False)
    # ### end Alembic commands ###
