apiVersion: v2
name: app
description: Transportation Forms — umbrella chart (backend + frontend)
type: application
version: 0.3.0
appVersion: "2.0.0"
keywords:
  - transportation-forms
  - bcgov
  - openshift
home: https://github.com/bcgov/transportation-forms
maintainers:
  - name: BCGov Transportation Forms Team
dependencies:
  - name: backend
    version: "1.0.0"
    repository: "file://../backend"
  - name: frontend
    version: "1.0.0"
    repository: "file://../frontend"
