# Crunchy PostgreSQL HA — TEST environment overrides
# Applied on top of values.yml

crunchy:
  instances:
    replicas: 2
    dataVolumeClaimSpec:
      storage: 2Gi
      storageClassName: netapp-block-standard

  proxy:
    pgBouncer:
      replicas: 2

  pgmonitor:
    enabled: false

  pgBackRest:
    pvc:
      fullBackupSchedule: "0 4 * * 0"
      incrementalBackupSchedule: "0 1 * * 1-6"
      volume:
        storage: 5Gi
        storageClassName: netapp-file-backup
