# Crunchy PostgreSQL HA — TEST environment overrides
# Applied on top of values.yml

crunchyPostgresHa:
  instances:
    - name: ha
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi

  proxy:
    pgBouncer:
      replicas: 2

  backups:
    pgbackrest:
      repos:
        - name: repo1
          schedules:
            full: "0 4 * * 0"
            differential: "0 1 * * 1-6"
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
