// frontend/js/views/reservation-form.js
// Reservation form wizard — extracted from index.html (Phase 5 refactor).
import { API_BASE } from '../constants.js';
import { escapeHtml, showAlert, formatReservationStatus } from '../utils.js';
import { getAuthToken } from '../auth.js';

// ─── Module-private state ────────────────────────────────────────────────────
let _loadedPrefixes = [];
let _generatedReservationId = null;

// ─── View entry point ─────────────────────────────────────────────────────────

export async function showReserveView() {
    _resetReservationForm();
    document.getElementById('reservationForm').style.display = 'block';
    document.getElementById('reservationSuccess').style.display = 'none';
    document.getElementById('reserveView').style.display = 'block';
    document.getElementById('pageTitle').textContent = 'Reserve Form Number - BC Gov';

    _attachDelegatedListeners();
    await loadPrefixes();
}

// ─── Delegated event wiring ───────────────────────────────────────────────────

let _listenersAttached = false;

function _attachDelegatedListeners() {
    if (_listenersAttached) return;
    _listenersAttached = true;

    const reserveView = document.getElementById('reserveView');
    if (!reserveView) return;

    reserveView.addEventListener('click', (e) => {
        const action = e.target.closest('[data-action]')?.dataset.action;
        if (!action) return;

        e.preventDefault();

        switch (action) {
            case 'loadPrefixes':
                loadPrefixes();
                break;
            case 'generateFormNumber':
                generateFormNumber();
                break;
            case 'submitReservation':
                submitReservation();
                break;
            case 'resetAndNewReservation':
                resetAndNewReservation();
                break;
        }
    });

    reserveView.addEventListener('change', (e) => {
        if (e.target.name === 'numberingMethod') {
            onNumberingMethodChange(e.target.value);
        }
        if (e.target.id === 'reservePrefix') {
            _updateCustomPrefixDisplay();
        }
    });
}

// ─── Prefix loading ───────────────────────────────────────────────────────────

export async function loadPrefixes() {
    const select = document.getElementById('reservePrefix');
    const spinner = document.getElementById('prefixLoadingSpinner');
    const errorDiv = document.getElementById('prefixLoadError');

    spinner.style.display = 'block';
    errorDiv.style.display = 'none';

    try {
        const response = await fetch(`${API_BASE}/prefixes`, {
            headers: { 'Authorization': `Bearer ${getAuthToken()}` }
        });
        if (!response.ok) throw new Error('Failed to load prefixes');
        _loadedPrefixes = await response.json();

        select.innerHTML = '<option value="">Select a prefix...</option>';
        _loadedPrefixes.forEach(p => {
            const opt = document.createElement('option');
            opt.value = p.id;
            opt.textContent = p.prefix + (p.description ? ` — ${p.description}` : '');
            opt.dataset.prefix = p.prefix;
            select.appendChild(opt);
        });
    } catch (error) {
        errorDiv.style.display = 'block';
        console.error('Prefix load error:', error);
    } finally {
        spinner.style.display = 'none';
    }
}

// ─── Numbering method toggle ──────────────────────────────────────────────────

export function onNumberingMethodChange(method) {
    _clearReservationErrors();

    const resolvedMethod = method
        ?? document.querySelector('input[name="numberingMethod"]:checked')?.value;

    document.getElementById('autoGeneratedNumber').value = '';
    document.getElementById('customFormNumber').value = '';
    document.getElementById('customReason').value = '';
    _generatedReservationId = null;

    if (resolvedMethod === 'auto') {
        document.getElementById('autoNumberSection').style.display = 'block';
        document.getElementById('customNumberSection').style.display = 'none';
    } else if (resolvedMethod === 'custom') {
        document.getElementById('autoNumberSection').style.display = 'none';
        document.getElementById('customNumberSection').style.display = 'block';
        _updateCustomPrefixDisplay();
    }
}

// ─── Auto number generation ───────────────────────────────────────────────────

export async function generateFormNumber() {
    _clearReservationErrors();

    const prefixId = document.getElementById('reservePrefix').value;
    if (!prefixId) {
        _showFieldError('reservePrefix', 'Please select a prefix before generating a number.');
        return;
    }

    const btn = document.getElementById('generateNumberBtn');
    const spinner = document.getElementById('generateSpinner');
    btn.disabled = true;
    spinner.style.display = 'block';

    try {
        const response = await fetch(`${API_BASE}/reservations/generate`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${getAuthToken()}`
            },
            body: JSON.stringify({ prefix_id: prefixId })
        });

        if (!response.ok) {
            const err = await response.json();
            const detail = err.detail || 'Failed to generate number';
            if (response.status === 400 || response.status === 404) {
                const errContainer = document.getElementById('reservationErrors');
                errContainer.innerHTML = `<i class="fas fa-exclamation-triangle"></i> <strong>Prefix configuration error:</strong> ${escapeHtml(detail)}. Please select a different prefix or contact an administrator.`;
                errContainer.style.display = 'block';
            }
            throw new Error(detail);
        }

        const result = await response.json();
        document.getElementById('autoGeneratedNumber').value = result.full_form_number;
        _generatedReservationId = result.id;
        showAlert('Form number generated: ' + result.full_form_number, 'success');
    } catch (error) {
        _showFieldError('autoNumber', error.message);
    } finally {
        btn.disabled = false;
        spinner.style.display = 'none';
    }
}

// ─── Validation ───────────────────────────────────────────────────────────────

export function validateReservationForm() {
    _clearReservationErrors();
    let isValid = true;

    if (!document.getElementById('reservePrefix').value) {
        _showFieldError('reservePrefix', 'Please select a prefix.');
        isValid = false;
    }

    const method = document.querySelector('input[name="numberingMethod"]:checked')?.value;
    if (!method) {
        const errEl = document.getElementById('error-numberingMethod');
        if (errEl) {
            errEl.textContent = 'Please select a numbering method.';
            errEl.style.setProperty('display', 'block', 'important');
        }
        isValid = false;
    }

    if (method === 'auto') {
        if (!_generatedReservationId || !document.getElementById('autoGeneratedNumber').value) {
            _showFieldError('autoNumber', 'Please generate a number before submitting.');
            isValid = false;
        }
    }

    if (method === 'custom') {
        const customNumber = document.getElementById('customFormNumber').value.trim();
        if (!customNumber) {
            _showFieldError('customFormNumber', 'Please enter a form number.');
            isValid = false;
        } else if (!/^[a-zA-Z0-9]+$/.test(customNumber)) {
            _showFieldError('customFormNumber', 'Form number must be alphanumeric (letters and digits only).');
            isValid = false;
        } else {
            const prefixId = document.getElementById('reservePrefix').value;
            const selectedPrefix = _loadedPrefixes.find(p => p.id === prefixId);
            if (selectedPrefix?.max_number_length && customNumber.length > selectedPrefix.max_number_length) {
                _showFieldError('customFormNumber', `Form number exceeds maximum length of ${selectedPrefix.max_number_length} characters.`);
                isValid = false;
            }
        }

        const reason = document.getElementById('customReason').value.trim();
        if (!reason) {
            _showFieldError('customReason', 'Please provide a reason for the custom number request.');
            isValid = false;
        }
    }

    return isValid;
}

// ─── Submission ───────────────────────────────────────────────────────────────

export async function submitReservation() {
    if (!validateReservationForm()) return;

    const method = document.querySelector('input[name="numberingMethod"]:checked').value;
    const prefixId = document.getElementById('reservePrefix').value;
    const submitBtn = document.getElementById('submitReservationBtn');
    const loadingOverlay = document.getElementById('submissionLoading');
    const loadingText = document.getElementById('submissionLoadingText');

    submitBtn.disabled = true;
    loadingOverlay.style.display = 'flex';

    try {
        let reservationId;
        let fullFormNumber;
        let numberingMethodLabel;

        if (method === 'auto') {
            reservationId = _generatedReservationId;
            fullFormNumber = document.getElementById('autoGeneratedNumber').value;
            numberingMethodLabel = 'Auto-generated';
        } else {
            loadingText.textContent = 'Reserving custom number...';
            const customNumber = document.getElementById('customFormNumber').value.trim();
            const reason = document.getElementById('customReason').value.trim();

            const reserveResponse = await fetch(`${API_BASE}/reservations/custom`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${getAuthToken()}`
                },
                body: JSON.stringify({
                    prefix_id: prefixId,
                    form_number: customNumber,
                    reason: reason
                })
            });

            if (!reserveResponse.ok) {
                const err = await reserveResponse.json();
                const detail = err.detail || 'Failed to reserve custom number';
                if (reserveResponse.status === 409) {
                    _showFieldError('customFormNumber', detail);
                    throw new Error(detail);
                }
                if (reserveResponse.status === 400 || reserveResponse.status === 404) {
                    const errContainer = document.getElementById('reservationErrors');
                    errContainer.innerHTML = `<i class="fas fa-exclamation-triangle"></i> ${escapeHtml(detail)}`;
                    errContainer.style.display = 'block';
                    throw new Error(detail);
                }
                throw new Error(detail);
            }

            const reserveResult = await reserveResponse.json();
            reservationId = reserveResult.id;
            fullFormNumber = reserveResult.full_form_number;
            numberingMethodLabel = 'Custom';
        }

        loadingText.textContent = 'Submitting for approval...';
        const submitResponse = await fetch(`${API_BASE}/reservations/${reservationId}/submit`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${getAuthToken()}`
            }
        });

        if (!submitResponse.ok) {
            const err = await submitResponse.json();
            throw new Error(err.detail || 'Failed to submit for approval');
        }

        const submittedResult = await submitResponse.json();

        showReservationSuccess({
            fullFormNumber,
            method: numberingMethodLabel,
            status: submittedResult.status || 'pending_approval',
            reason: method === 'custom' ? document.getElementById('customReason').value.trim() : null
        });

    } catch (error) {
        const hasInlineErrors =
            document.getElementById('reservationErrors').style.display !== 'none' ||
            document.querySelector('#reservationForm .is-invalid');
        if (!hasInlineErrors) {
            showAlert('Error: ' + error.message, 'danger');
        }
    } finally {
        submitBtn.disabled = false;
        loadingOverlay.style.display = 'none';
    }
}

// ─── Success confirmation panel ───────────────────────────────────────────────

export function showReservationSuccess(data) {
    document.getElementById('reservationForm').style.display = 'none';
    const successPanel = document.getElementById('reservationSuccess');

    document.getElementById('successFormNumber').textContent = data.fullFormNumber;
    document.getElementById('successMethod').textContent = data.method;

    const statusBadge = document.getElementById('successStatus');
    statusBadge.textContent = formatReservationStatus(data.status);
    statusBadge.className = 'badge reservation-status-badge status-' + data.status;

    if (data.reason) {
        document.getElementById('successReasonLabel').style.display = '';
        document.getElementById('successReason').style.display = '';
        document.getElementById('successReason').textContent = data.reason;
    } else {
        document.getElementById('successReasonLabel').style.display = 'none';
        document.getElementById('successReason').style.display = 'none';
    }

    successPanel.style.display = 'block';
    showAlert('Reservation submitted successfully — awaiting approval', 'success');
    window.scrollTo(0, 0);
}

// ─── Reset / new reservation ──────────────────────────────────────────────────

export function resetAndNewReservation() {
    document.getElementById('reservationSuccess').style.display = 'none';
    document.getElementById('reservationForm').style.display = 'block';
    _resetReservationForm();
    loadPrefixes();
}

// ─── Private helpers ──────────────────────────────────────────────────────────



function _resetReservationForm() {
    const form = document.getElementById('reservationForm');
    if (form) form.reset();
    _generatedReservationId = null;

    document.getElementById('autoNumberSection').style.display = 'none';
    document.getElementById('customNumberSection').style.display = 'none';
    document.getElementById('autoGeneratedNumber').value = '';
    document.getElementById('customFormNumber').value = '';
    document.getElementById('customReason').value = '';
    document.getElementById('customPrefixDisplay').textContent = '--';

    _clearReservationErrors();
}

function _clearReservationErrors() {
    ['reservePrefix', 'numberingMethod', 'autoNumber', 'customFormNumber', 'customReason'].forEach(id => {
        const el = document.getElementById('error-' + id);
        if (el) {
            el.style.display = 'none';
            el.style.setProperty('display', 'none', 'important');
        }
    });
    ['reservePrefix', 'customFormNumber', 'customReason'].forEach(id => {
        const input = document.getElementById(id);
        if (input) input.classList.remove('is-invalid');
    });
    document.querySelectorAll('.reservation-method-option').forEach(opt => opt.classList.remove('is-invalid'));
    const errBox = document.getElementById('reservationErrors');
    if (errBox) { errBox.style.display = 'none'; errBox.textContent = ''; }
}

function _showFieldError(fieldId, message) {
    const el = document.getElementById('error-' + fieldId);
    if (el) {
        el.textContent = message;
        el.style.display = 'block';
        el.style.setProperty('display', 'block', 'important');
    }
    const input = document.getElementById(fieldId);
    if (input) input.classList.add('is-invalid');
}

function _updateCustomPrefixDisplay() {
    const select = document.getElementById('reservePrefix');
    const selectedOption = select.options[select.selectedIndex];
    const prefixText = selectedOption?.dataset.prefix ?? '--';
    document.getElementById('customPrefixDisplay').textContent = prefixText;
}
