# Crunchy PostgreSQL HA — TEST environment overrides
# Applied on top of values.yml

crunchy:
  instances:
    replicas: 2
    dataVolumeClaimSpec:
      storage: 2Gi
      walStorage: 512Mi
    requests:
      cpu: 250m
      memory: 512Mi

  proxy:
    pgBouncer:
      replicas: 2

  pgBackRest:
    pvc:
      fullBackupSchedule: "0 4 * * 0"
      incrementalBackupSchedule: "0 1 * * 1-6"
      volume:
        storage: 5Gi
