{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "public-backend.fullname" . }}
  labels:
    {{- include "public-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: public-backend
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "public-backend.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: public-backend
{{- end }}
