apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
{{ toYaml .Values.app.labels | indent 4 }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
  type: {{ .Values.app.service.type }}
