{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.postgres.name }}
spec:
  selector:
    app: {{ .Values.postgres.name }}
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.containerPort }}
{{- end }}
