apiVersion: v1
kind: Service
metadata:
  name: {{ include "public-frontend.fullname" . }}
  labels:
    {{- include "public-frontend.labels" . | nindent 4 }}
    app.kubernetes.io/component: public-frontend
spec:
  type: ClusterIP
  selector:
    {{- include "public-frontend.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: public-frontend
  ports:
    - name: traffic
      port: {{ .Values.servicePort }}
      targetPort: http
      protocol: TCP
    - name: health
      port: {{ .Values.healthPort }}
      targetPort: health
      protocol: TCP
