name: Deploy DEV OpenShift

on:
  push:
    branches: [ "master" ]
    paths-ignore:
    - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Push Image

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Log in to OpenShift Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ vars.OPENSHIFT_IMAGESTREAM_URL }}
          username: ${{ secrets.OPENSHIFT_IMAGESTREAM_USERNAME }}
          password: ${{ secrets.OPENSHIFT_IMAGESTREAM_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{ vars.OPENSHIFT_IMAGESTREAM_URL }}transportation-forms
          tags: |
            type=raw,value=latest
            type=raw,value=latest-dev
            type=sha,format=long

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push to both registries
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            app=transportation-forms

